// Generates CODEMAP.md — a line-numbered index of map.html.
//
// map.html is one ~9k-line file (HTML + CSS + JS inline). To navigate it quickly
// it uses banner comments:
//     // ════…
//     //  SECTION TITLE
//     // ════…
// This script scans those banners plus every top-level `function` declaration and
// writes a grouped, line-numbered map so you can jump straight to code instead of
// grepping repeatedly.
//
// Run from the repo root:  node scripts/gen-codemap.js
// Re-run after edits — line numbers drift, the banner titles do not (grep those).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root    = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC     = join(root, 'map.html');
const OUT     = join(root, 'CODEMAP.md');

const lines = readFileSync(SRC, 'utf8').split(/\r?\n/);
const isBanner = s => /^\/\/\s*═{6,}\s*$/.test(s);
const fnRe     = /^\s*(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/;

// Pass 1: collect banner sections (title line = the `//  TITLE` between two ═ lines)
const sections = [];   // { line, title }
for (let i = 1; i < lines.length - 1; i++) {
  if (isBanner(lines[i - 1]) && isBanner(lines[i + 1])) {
    const m = lines[i].match(/^\/\/\s+(.*\S)\s*$/);
    if (m) sections.push({ line: i + 1, title: m[1] });   // 1-based line number
  }
}

// Pass 2: collect top-level function declarations
const fns = [];        // { line, name }
for (let i = 0; i < lines.length; i++) {
  const m = lines[i].match(fnRe);
  if (m) fns.push({ line: i + 1, name: m[1] });
}

// Assign each function to the nearest preceding section
function sectionFor(lineNo) {
  let cur = null;
  for (const s of sections) { if (s.line <= lineNo) cur = s; else break; }
  return cur;
}
const bySection = new Map();           // title → { line, fns: [] }
const preamble  = [];                  // functions before the first banner
for (const s of sections) bySection.set(s.title, { line: s.line, fns: [] });
for (const fn of fns) {
  const s = sectionFor(fn.line);
  if (s) bySection.get(s.title).fns.push(fn);
  else preamble.push(fn);
}

// Emit
const stamp = new Date().toISOString().slice(0, 10);
let out = `# map.html — Code Map\n\n`;
out += `> Auto-generated by \`scripts/gen-codemap.js\`. **Do not edit by hand.**\n`;
out += `> Regenerate after changing map.html: \`node scripts/gen-codemap.js\`\n`;
out += `> Line numbers drift between regenerations — the **section titles are stable grep anchors**\n`;
out += `> (e.g. \`grep -n "CLIMATE MATCH" map.html\`).\n\n`;
out += `Source: \`map.html\` · ${lines.length} lines · ${sections.length} sections · ${fns.length} top-level functions · generated ${stamp}\n\n`;

// Section index
out += `## Sections\n\n`;
for (const s of sections) out += `- **L${s.line}** — ${s.title}\n`;
out += `\n`;

// Per-section function lists
out += `## Functions by section\n\n`;
if (preamble.length) {
  out += `### (before first banner)\n\n`;
  for (const fn of preamble) out += `- \`${fn.name}\` — L${fn.line}\n`;
  out += `\n`;
}
for (const s of sections) {
  const bucket = bySection.get(s.title);
  out += `### L${s.line} — ${s.title}\n\n`;
  if (bucket.fns.length) for (const fn of bucket.fns) out += `- \`${fn.name}\` — L${fn.line}\n`;
  else out += `_(no top-level functions — CSS/HTML/constants)_\n`;
  out += `\n`;
}

// Alphabetical function lookup
out += `## All functions (A→Z)\n\n`;
for (const fn of [...fns].sort((a, b) => a.name.localeCompare(b.name))) {
  out += `- \`${fn.name}\` — L${fn.line}\n`;
}
out += `\n`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT}: ${sections.length} sections, ${fns.length} functions, ${lines.length} source lines.`);
